import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { GeneratedPlan, UserInputs } from '../types';

export const generateProgrammaticPDF = async (plan: GeneratedPlan, inputs: UserInputs, userName: string) => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2);

  // Helper for colors
  const colors = {
    neon: [204, 255, 0], // RGB for #CCFF00
    dark: [9, 9, 11],    // RGB for #09090B
    zinc800: [39, 39, 42],
    zinc500: [113, 113, 122],
    white: [255, 255, 255],
  };

  // --- PAGE 1: COVER ---
  // Background
  doc.setFillColor(colors.dark[0], colors.dark[1], colors.dark[2]);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  // Decorative neon circle (subtle)
  doc.setDrawColor(colors.neon[0], colors.neon[1], colors.neon[2]);
  doc.setLineWidth(0.5);
  doc.setGState(new (doc as any).GState({ opacity: 0.1 }));
  doc.circle(pageWidth, 0, 80, 'F');
  doc.setGState(new (doc as any).GState({ opacity: 1.0 }));

  // Branding
  doc.setTextColor(colors.neon[0], colors.neon[1], colors.neon[2]);
  doc.setFont('helvetica', 'bolditalic');
  doc.setFontSize(40);
  doc.text('FITIN60.AI', pageWidth / 2, 80, { align: 'center' });

  doc.setTextColor(colors.white[0], colors.white[1], colors.white[2]);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('YOUR AI-POWERED ELITE PROTOCOL', pageWidth / 2, 95, { align: 'center' });

  // User Name
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(userName.toUpperCase(), pageWidth / 2, 130, { align: 'center' });
  
  doc.setDrawColor(colors.neon[0], colors.neon[1], colors.neon[2]);
  doc.setLineWidth(1);
  doc.line(pageWidth / 2 - 20, 135, pageWidth / 2 + 20, 135);

  // Summary Box
  const summaryY = 150;
  doc.setFillColor(colors.zinc800[0], colors.zinc800[1], colors.zinc800[2]);
  doc.roundedRect(margin, summaryY, contentWidth, 80, 5, 5, 'F');

  doc.setTextColor(colors.neon[0], colors.neon[1], colors.neon[2]);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text("COACH'S BRIEF", margin + 10, summaryY + 12);

  doc.setTextColor(colors.white[0], colors.white[1], colors.white[2]);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  const summaryText = plan.personalizedSummary ? `"${plan.personalizedSummary}"` : '"Your personalized plan details are being processed."';
  const splitSummary = doc.splitTextToSize(summaryText, contentWidth - 20);
  doc.text(splitSummary, margin + 10, summaryY + 22);

  const statsY = summaryY + 45;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const summaryItems = [
    `Goal: ${inputs.primaryGoal}`,
    `Duration: ${inputs.planDuration}`,
    `Level: ${inputs.fitnessLevel}`,
    `Location: ${inputs.workoutLocation}`
  ];
  
  summaryItems.forEach((item, i) => {
    doc.text(item, margin + 10, statsY + (i * 6));
  });

  const statsX = pageWidth / 2 + 10;
  const statsItems = [
    `Age: ${inputs.age} yrs`,
    `Height: ${inputs.height} ${inputs.heightUnit}`,
    `Weight: ${inputs.weight} ${inputs.weightUnit}`,
    `Gender: ${inputs.gender}`
  ];

  statsItems.forEach((item, i) => {
    doc.text(item, statsX, statsY + (i * 6));
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(colors.zinc500[0], colors.zinc500[1], colors.zinc500[2]);
  doc.text('© 2026 FITIN60.AI • GENERATED BY GEN-Z AI ENGINE', pageWidth / 2, pageHeight - 15, { align: 'center' });

  // --- PAGE 2: COACHING INSIGHTS & WORKOUT ---
  doc.addPage();
  doc.setFillColor(colors.white[0], colors.white[1], colors.white[2]);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  // Header
  doc.setFillColor(colors.dark[0], colors.dark[1], colors.dark[2]);
  doc.rect(0, 0, pageWidth, 30, 'F');
  doc.setTextColor(colors.neon[0], colors.neon[1], colors.neon[2]);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bolditalic');
  doc.text('01 COACHING INSIGHTS', margin, 20);

  let currentY = 45;
  
  (plan.coachingTips || []).forEach((tip, i) => {
    doc.setFillColor(colors.dark[0], colors.dark[1], colors.dark[2]);
    doc.roundedRect(margin, currentY, contentWidth, 20, 3, 3, 'F');
    
    doc.setTextColor(colors.neon[0], colors.neon[1], colors.neon[2]);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('TIP ' + (i + 1), margin + 5, currentY + 8);
    
    doc.setTextColor(colors.white[0], colors.white[1], colors.white[2]);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const splitTip = doc.splitTextToSize(tip, contentWidth - 30);
    doc.text(splitTip, margin + 25, currentY + 8);
    
    currentY += 25;
  });

  currentY += 10;

  // Workout Header
  doc.setTextColor(colors.dark[0], colors.dark[1], colors.dark[2]);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bolditalic');
  doc.text('02 TRAINING PROTOCOL', margin, currentY);
  currentY += 10;

  (plan.workout?.weeklySplit || []).forEach((day, dayIndex) => {
    // Check if we need a new page
    if (currentY > pageHeight - 60) {
      doc.addPage();
      currentY = 20;
    }

    doc.setTextColor(colors.dark[0], colors.dark[1], colors.dark[2]);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(`${day.day || 'Day'}: ${day.focus || 'Workout'}`, margin, currentY);
    currentY += 5;

    if (day.dayPurpose) {
      doc.setTextColor(colors.zinc500[0], colors.zinc500[1], colors.zinc500[2]);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      doc.text(day.dayPurpose, margin, currentY);
      currentY += 5;
    }

    autoTable(doc, {
      startY: currentY,
      head: [['Exercise', 'Sets x Reps', 'Rest', 'Notes']],
      body: (day.exercises || []).map(ex => [
        ex.name || 'Exercise',
        ex.setsReps || '-',
        ex.rest || '-',
        ex.notes || '-'
      ]),
      theme: 'striped',
      headStyles: {
        fillColor: [9, 9, 11],
        textColor: [204, 255, 0],
        fontSize: 9,
        fontStyle: 'bold',
      },
      bodyStyles: {
        fontSize: 8,
        textColor: [39, 39, 42],
      },
      margin: { left: margin, right: margin },
      didDrawPage: (data) => {
        currentY = data.cursor ? data.cursor.y + 15 : currentY + 15;
      }
    });
  });

  // --- PAGE 3: NUTRITION PLAN ---
  doc.addPage();
  doc.setFillColor(colors.white[0], colors.white[1], colors.white[2]);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  // Header
  doc.setFillColor(colors.dark[0], colors.dark[1], colors.dark[2]);
  doc.rect(0, 0, pageWidth, 30, 'F');
  doc.setTextColor(colors.neon[0], colors.neon[1], colors.neon[2]);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bolditalic');
  doc.text('03 FUELING STRATEGY', margin, 20);

  currentY = 45;

  // Macros Box
  doc.setFillColor(colors.zinc800[0], colors.zinc800[1], colors.zinc800[2]);
  doc.roundedRect(margin, currentY, contentWidth, 30, 3, 3, 'F');
  
  doc.setTextColor(colors.neon[0], colors.neon[1], colors.neon[2]);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(`${plan.diet?.dailyCalories || '0'} KCAL`, margin + 10, currentY + 12);

  doc.setTextColor(colors.white[0], colors.white[1], colors.white[2]);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`PROTEIN: ${plan.diet?.macros?.protein || '0g'}  |  CARBS: ${plan.diet?.macros?.carbs || '0g'}  |  FATS: ${plan.diet?.macros?.fats || '0g'}`, margin + 10, currentY + 22);

  currentY += 45;

  // Diet Strategy Tips
  if (plan.dietStrategyTips && plan.dietStrategyTips.length > 0) {
    doc.setTextColor(colors.dark[0], colors.dark[1], colors.dark[2]);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('DIET STRATEGY TIPS', margin, currentY);
    currentY += 5;
    
    plan.dietStrategyTips.forEach((tip, i) => {
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.text(`• ${tip}`, margin + 5, currentY);
      currentY += 5;
    });
    currentY += 5;
  }

  (plan.diet?.weeklySchedule || []).forEach((day, dayIndex) => {
    if (currentY > pageHeight - 60) {
      doc.addPage();
      currentY = 20;
    }

    doc.setTextColor(colors.dark[0], colors.dark[1], colors.dark[2]);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(day.day || 'Day', margin, currentY);
    currentY += 5;

    autoTable(doc, {
      startY: currentY,
      head: [['Meal', 'Options', 'Alternatives']],
      body: (day.meals || []).map(meal => [
        meal.name || 'Meal',
        (meal.options || []).join('\n'),
        meal.alternatives || '-'
      ]),
      theme: 'grid',
      headStyles: {
        fillColor: [9, 9, 11],
        textColor: [204, 255, 0],
        fontSize: 9,
      },
      bodyStyles: {
        fontSize: 8,
        cellPadding: 3,
      },
      columnStyles: {
        0: { fontStyle: 'bold', cellWidth: 25 },
        1: { cellWidth: 100 },
        2: { fontStyle: 'italic' }
      },
      margin: { left: margin, right: margin },
      didDrawPage: (data) => {
        currentY = data.cursor ? data.cursor.y + 10 : currentY + 10;
      }
    });
  });

  // Safety Notes
  const lastY = (doc as any).lastAutoTable.finalY || currentY + 100;
  currentY = lastY + 15;

  if (currentY > pageHeight - 60) {
    doc.addPage();
    currentY = 20;
  }

  doc.setFillColor(255, 241, 242); // Light red background for safety
  doc.setDrawColor(225, 29, 72); // Red border
  doc.roundedRect(margin, currentY, contentWidth, 40, 3, 3, 'FD');

  doc.setTextColor(159, 18, 57);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('SAFETY PROTOCOL & DISCLAIMER', margin + 5, currentY + 8);

  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  const safetyText = (plan.safetyNotes || []).join(' • ') + ' • Medical Disclaimer: This plan is AI-generated and for educational purposes only. Consult a doctor before starting.';
  const splitSafety = doc.splitTextToSize(safetyText, contentWidth - 10);
  doc.text(splitSafety, margin + 5, currentY + 15);

  // Save the PDF
  doc.save(`fitin60-plan-${userName.toLowerCase().replace(/\s+/g, '-')}.pdf`);
};
