import React from 'react';
import { motion } from 'motion/react';
import { AlertTriangle, ShieldAlert, Stethoscope, Info } from 'lucide-react';
import SEO from '../components/SEO';

const DisclaimerPage: React.FC = () => {
  return (
    <div className="pt-32 pb-20 px-4 md:px-8 max-w-4xl mx-auto">
      <SEO 
        title="Medical Disclaimer | Fitin60ai.in Safety Information"
        description="Important medical disclaimer for Fitin60ai.in. Please read our safety guidelines before using our AI-generated fitness and diet plans."
        canonical="https://fitin60ai.in/disclaimer"
      />

      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="text-center mb-16"
      >
        <div className="inline-flex p-4 bg-amber-500/10 rounded-2xl mb-6">
          <AlertTriangle className="w-12 h-12 text-amber-500" />
        </div>
        <h1 className="text-4xl md:text-6xl font-black uppercase italic tracking-tighter mb-6">
          Medical <span className="text-amber-500">Disclaimer</span>
        </h1>
        <p className="text-zinc-400 text-lg font-medium">
          Please read this disclaimer carefully before using any information or plans provided by Fitin60ai.in.
        </p>
      </motion.div>

      <div className="space-y-12 text-zinc-400 leading-relaxed">
        <section className="bg-zinc-900/30 border border-white/5 p-8 rounded-[2rem]">
          <div className="flex items-center gap-4 mb-4">
            <Stethoscope className="w-6 h-6 text-neon" />
            <h2 className="text-xl font-black uppercase italic tracking-tight text-white">Not Medical Advice</h2>
          </div>
          <p>
            The content on Fitin60ai.in, including but not limited to text, graphics, images, AI-generated workout plans, and diet protocols, is for informational and educational purposes only. It is NOT intended to be a substitute for professional medical advice, diagnosis, or treatment.
          </p>
          <p className="mt-4">
            Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition or before starting any new exercise or nutrition program.
          </p>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-4 mb-2">
            <ShieldAlert className="w-6 h-6 text-neon" />
            <h2 className="text-xl font-black uppercase italic tracking-tight text-white">Assumption of Risk</h2>
          </div>
          <p>
            By using our AI-generated plans, you acknowledge that physical exercise involves inherent risks of injury. You voluntarily assume all risks associated with any exercise or nutrition program you choose to follow. Fitin60ai.in and its creators are not responsible for any injuries, health problems, or death that may result from your use of our services.
          </p>
        </section>

        <section className="space-y-4">
          <div className="flex items-center gap-4 mb-2">
            <Info className="w-6 h-6 text-neon" />
            <h2 className="text-xl font-black uppercase italic tracking-tight text-white">AI Limitations</h2>
          </div>
          <p>
            Our plans are generated by Artificial Intelligence algorithms. While we strive for accuracy and safety, AI can make mistakes. The plans do not take into account your specific medical history, current injuries, or unique physiological needs unless explicitly provided, and even then, the AI's understanding is limited.
          </p>
          <p>
            If you experience any pain, dizziness, shortness of breath, or discomfort while following a plan, STOP IMMEDIATELY and consult a medical professional.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-black uppercase italic tracking-tight text-white">No Guarantees</h2>
          <p>
            Fitin60ai.in makes no guarantees regarding the results that may be achieved from following our plans. Individual results vary based on genetics, effort, consistency, and other environmental factors.
          </p>
        </section>

        <div className="pt-8 border-t border-white/5 text-sm italic">
          Last Updated: April 7, 2026
        </div>
      </div>
    </div>
  );
};

export default DisclaimerPage;
